version: "3.8"
services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    logging:
      driver: none

  redisdb:
    container_name: redisdb
    image: redis:latest
    ports:
        - ${REDIS_PORT}:6379
    logging:
        driver: none